- name: Debug input
  debug:
    msg: "{{ outer_item }}"

- name: "Create PVC in OCS"
  ignore_errors: yes
  k8s:
    state: present
    definition: "{{ lookup('template', 'pvc.yml.j2') }}"
  register: pvc_create_output
