---
- hosts: localhost
  vars_files:
    - vars/run-rsync.yml
    - vars/defaults.yml
  tasks:
    - import_tasks: ../common/assert-kubeconfig.yml
      tags:
      - assert_kubeconfig

    - import_tasks: ../common/assert-vars.yml

    - name: Load pvc data from output file
      tags:
      - load_vars
      set_fact:
        pvc_data: "{{ lookup('file', pvc_data_filepath) | from_json }}"

    - name: "Create pod and service - one namespace at a time"
      include_tasks: tasks/create-rsync-jobs.yml
      with_items: "{{ pvc_data }}"
