# This task starts one kubernetes job per PVC that is supposed to be migrated
# We wait until all the jobs are finished until we proceed

- debug: msg="{{ item }}"

- name: Start one Job per PVC we want to migrate
  loop: "{{ item.pvcs }}"
  loop_control:
    loop_var: pvc
  k8s:
    state: present
    definition: "{{ lookup('template', 'job.yml.j2') }}"

# - set_fact:
#     failed_pvcs: []
#     successful_pvcs: []


- name: Wait until all Jobs are finished
  loop: "{{ item.pvcs }}"
  loop_control:
    loop_var: pvc
  include_tasks: wait_for_job.yml

# - name: "Printing failed / succeded pvcs"
#   debug:
#     msg: "{{ failed_pvcs }} {{ successful_pvcs }}"

# - name: "Dumping failure report"
#   copy:
#     content: "{{ failed_pvcs | to_json }}"
#     dest: "{{ failed_pvcs_dir }}/{{ pvc_namespace }}-failed.json"

# - name: "Dumping success report"
#   copy:
#     content: "{{ successful_pvcs | to_json }}"
#     dest: "{{ successful_pvcs_dir }}/{{ pvc_namespace }}-successful.json"
